# Site settings
title: Caneta's tech blog
email: canduc17@gmail.com
description: Technical blog test
url: "https://caneta.github.com"
twitter_username: canduc17
github_username:  caneta

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
